Add homarr-iframes project note in the iframes widget docs
homarr-labs/documentation pull request #66
Opened 2024-04-12 20:58 UTC by diogovalentte

### Category
>Documentation.

### Overview
> I made a [post on reddit](https://www.reddit.com/r/selfhosted/comments/1c0qp0i/comment/kyztyqi/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) showing my Homarr dashboard with iframes of my project, [homarr-iframes](github.com/diogovalentte/homarr-iframes). A Homarr dev asked me if I wanted to link the project on the official documentation, so there is.

> I don't know if the iframe widget page is the best place to put it, or if the note I added is too big, so you can change it if you decide to add it.

### Screenshot
![image](https://github.com/homarr-labs/documentation/assets/49578155/432b4887-6a52-4045-84ba-295d834824ac)

2024-04-15 01:28 UTC, manuel-rw requested changes

2024-04-15 01:28 UTC, manuel-rw commented on docs/widgets/iframe/index.mdx
> +## homarr-iframes
Please adjust the title structure:

```
## Third party content
### homarr-iframes from YOUR_NAME
```

2024-04-15 01:28 UTC, manuel-rw commented on docs/widgets/iframe/index.mdx
> +## homarr-iframes
Add an info using this tool  https://docusaurus.io/docs/markdown-features/admonitions and mention that this is third party content and all support requests / problems must be redirected to the appropriate repository.

2024-04-15 01:28 UTC, manuel-rw commented on docs/widgets/iframe/index.mdx
> +The project [homarr-iframes](https://github.com/diogovalentte/homarr-iframes) has iframes designed to be used with Homarr. These iframes offer a minimalist view of other systems, like viewing your ta
There is some ballast here.
Remove ``other systems, like`` and just make a bullet point list with the apps supported and what you can do with them:
```md
- go-vikunja: Do X, Y and Z
- linkwarden: Do U and Z
```

2024-04-15 01:28 UTC, manuel-rw commented on docs/widgets/iframe/index.mdx
> +![](./homarr-iframes-example.webp)
Add an alternative text to this image. Can be useful for blind people and screen readers.

2024-04-15 01:28 UTC, manuel-rw commented on docs/widgets/iframe/index.mdx
> +The iframes have options for configuration, like selecting the iframe theme and limit, and other options specific to each iframe.
Perhaps link to these options or the documentation about them?

2024-04-15 15:33 UTC, diogovalentte commented
Thanks for your feedback, I updated the docs.

2024-04-18 08:38 UTC, ajnart approved these changes
LGTM ! Cool project 😎

2024-04-18 08:38 UTC, merged